services:
  mongo:
    image: mongo:6.0
    container_name: mongo_order
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    env_file:
      - ../../envs/.order.env

volumes:
  mongo_data:
