services:
  mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

volumes:
  mongo_data:
